"""Что логике диалога нужно от Telegram. Реализации: app.TelegramIo и tests.fakes.FakeIo."""
from __future__ import annotations

from typing import Protocol

Buttons = list[list[tuple[str, str]]]  # строки кнопок: (надпись, callback_data)


class Io(Protocol):
    async def reply(self, text: str, buttons: Buttons | None = None) -> None: ...

    async def download(self, file_id: str) -> bytes: ...

    async def send_admin(self, text: str, buttons: Buttons | None = None) -> tuple[int, int]: ...

    async def edit_admin(self, ref: tuple[int, int], text: str) -> None: ...

    async def send_user(self, tg_user_id: int, text: str, buttons: Buttons | None = None) -> None: ...

    async def answer_button(self, text: str | None = None, remove_keyboard: bool = True) -> None: ...

    def kick_background(self) -> None: ...


class SheetReader(Protocol):
    async def hr_status(self, number: str) -> str | None: ...
